### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by mattdavis0351** [ionnovate/Kese-Sweat-Day-1-Exercise#2]
Hi 👋 

I have created [this pr](#1 ).  Follow the task in the pull request body!

**additional tasks outside of the pr**

- Assign someone other than @mattdavis0351 or yourself to this issue
- Create a custom label in this repo called `day 2 stuffs` and add it to this issue
- reference this issue in a comment on the pull request mentioned above

**Comment by Kese-Sweat** [comment]
Created a custom label
